apiVersion: v1
kind: Pod
metadata:
  name: init
  labels:
    app: init
spec:
  containers:
  - image: mpgagebioinformatics/myapp:latest #hub.age.mpg.de/flaski/server
    imagePullPolicy: Always
    name: init
    command: ["/myapp/services/init/entrypoint.sh"]
    securityContext:
      allowPrivilegeEscalation: false
      runAsUser: 0
    env:
    - name: APP_NAME
      value: myapp
    - name: APP_TITLE
      value: myapp
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: myapp-secrets
          key: SECRET_KEY
    - name: FLASK_ENV
      value: init
    - name: RESTORE_DB
      value: "1"
    - name: RESTORE_USERS_DATA
      value: "1"
    - name: MAIL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: flaskimailpass
          key: pass
    - name: MYSQL_HOST
      value: mariadb
    - name: MYSQL_PORT
      value: "3306"
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: myapp-secrets
          key: MYSQL_ROOT_PASSWORD
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: myapp-secrets
          key: MYSQL_PASSWORD
    - name: MYSQL_USER
      value: myapp
    - name: REDIS_ADDRESS
      value: redis:6379/0
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: myapp-secrets
          key: REDIS_PASSWORD
    - name: ADMINS
      value: flaski@age.mpg.de
    resources: {}
    volumeMounts:
    - name: users-volume-mount
      mountPath: /myapp_data/users/
    - name: backup-volume-mount
      mountPath: /backup      
  restartPolicy: OnFailure
  imagePullSecrets:
    - name: dockerlogin
  volumes:
  - name: users-volume-mount
    persistentVolumeClaim:
      claimName: users-pvc
  - name: backup-volume-mount
    persistentVolumeClaim:
      claimName: bc-pvc

status: {}
